#!/bin/bash
# This is a comment

echo "The current directory is:"

pwd

echo "The user logged in is:"

whoami

echo "Go to terminal:"

cd Terminal

echo "add 3 folders:"

mkdir folder1 folder2 folder3

echo "go to folder3:"

cd folder3

echo "add 5 new files:"

touch 1.txt 2.txt 3.txt 1.json 2.json

echo "add 3 folders:"

mkdir 1folder 2folder 3folder

echo "ls -la"

ls -la

mv 1.txt 1.json 3folder

